### ISSUE TITLE
How to use OSNMA lib with Ublox F9R ??? 

### ISSUE THREAD

**Issue by mirecta** [Algafix/OSNMA#16]
I cant find anything usable. I will try read 
SFRBX messages from Ublox but i cant separate E1B INAV messages from another one and this message not tontain seconds for frame sync 
can anybody help me ?

**Comment by Algafix** [comment]
Hello Mirecta!

Currently there's no input module for ublox messages for OSNMAlib. If you are willing to wait, someone is working on it and should be included in the repository in one month from now.

In the meantime, I can only point you to the [input data wiki page] (https://github.com/Algafix/OSNMA/wiki/Input-Data#concept) in case you want to try to implement it yourself.

My experience with ublox is very limited, but I assume you can filter those messages you mention based on some signal field. For the seconds for frame sync, maybe another ublox message can give you that information. Remember that the input pages to OSNMAlib have to indicate the WN and ToW of **transmission**; and due to the nature of E1B INAV that will be in a 2 seconds basis.

Maybe someone else can give you another idea. And thanks for the interest :D
