### ISSUE TITLE
SBF file parsing

### ISSUE THREAD

**Issue by FayeWong98** [Algafix/OSNMA#3]
I have an osnma certified SBF file. Can I import it directly into osnmalib for parsing? Because I see that the public key and other files are used in the project.

**Comment by Algafix** [comment]
Hi!

Yes, you can. The folder `custom_run/` is prepared with and script to automatically run you own SBF file. The folder contains the Public Key and Merkle Tree root values currently in transmission. If your SBF file is older than October 2021 you'll need to provide your own Public Key and Merkle Tree files (if your SBF file contains a public key transmission then you only need the Merkle Tree). The filenames are hardcoded in the `run.py` script, so make sure to change them.

For more information, please check the section in the [readme](https://github.com/Algafix/OSNMA#quick-run-your-own-sbf-file)

**Comment by FayeWong98** [comment]
Thank you for your reply. I noticed that GSTsf is used in the key and tag verification phase of osnma. It comes from the Galileo subframe and is generated once every 30s (30, 60, 90...). And if the current subframe is lost and the key is resolved in the next frame, the authentication can still be completed.

Therefore, I have some confusion. If the Galileo signal I received is delayed for 10s (or other values), since the parsed GSTsf is still the tow number in the current 30s subframe - for example, K0 and K1 have been verified, and I delay K2 for 10s, the parsed GSTsf's tow is still 60, meeting the increment of 0-30-60, will this affect the osnma authentication?

**Comment by Algafix** [comment]
So, the OSNMAlib is not a receiver, it is not resolving the time (or position for what matters). It is piggybacking in another receiver (the one that generated the SBF file) to get the subframe times. The subframe times are part of the SBF file and this is what the OSNMAlib is assuming as time of subframe arrival.

Because you are reading from and SBF file, OSNMAlib has no mean of knowing if the subframe was delayed or not at reception, it'll just read the SBF file as fast as possible. As far as I know the SBF files do not save the time of arrival of a subframe.

A secure OSNMA implementation should take into account if the subframe was delayed or not (using a local time, a time from and NTP server or a time from a receiver). For example, a key cannot be received 30s delayed of its supposed arrival time (actually less than 30s). For more information about this time constrains I'll refer you to the official OSNMA documentation.

Going back to the topic, OSNMAlib is not a secure implementation time-wise because there's no receiver resolving the time. A few months ago I managed to implement a real-time parsing of OSNMA from an SFB stream. Now I could implement some kind of security in this sense, but it's not a priority for me because if someone wants to use this library in their receiver they will have a better time reference than anything I can imitate.

I think this solves your question, if I misunderstood, let me know :D

**Comment by FayeWong98** [comment]
Thank you for your reply, you are so enthusiastic!

In fact, after reading the Galileo osnma document and combining with osnmalib, I was puzzled. The official document does not seem to mention the consequences if a subframe is delayed, or how long the interval between two valid keys should be - 30s is only the interval between two keys transmitted from the satellite, not the interval received by the receiver.

The only thing I notice is that osnma must be synchronized with the receiver's time with TL = 30s and B < TL / 2. If this condition is not met, the receiver will not execute osnma. But is this related to the delay of a subframe I mentioned? This seems to be only a prerequisite for the receiver to perform osnma operation.

I look forward to your reply. If possible, I hope to discuss with you on gmail. Thank you!
