### ISSUE TITLE
OSNMALib and SBF

### ISSUE THREAD

**Issue by FayeWong98** [Algafix/OSNMA#4]
Hello, it is known that the Septentrio receiver can save the data in the entire OSNMA authentication process, and the SBF data can be analyzed by OSNMALib.

My confusion is whether the authentication algorithm implemented by OSNMALib and septentrio's internal chip is the same? In the authentication process, the receiver is authenticated in real time, and OSNMALib first uses the SBF file for parsing and authentication. Will their mechanisms be different?

Looking forward to your reply, I wish you a happy life!

Best，
Faye

**Comment by Algafix** [comment]
Hi,

OSNMAlib is not related to any private company. I use the Septentrio Binary Format because it is what I have available to debug and test. OSNMAlib only needs the bits, the WN-TOW, and the SVID; so any data containing those will work.
For example, I provide a way of running it with galmon or against the ICD test vectors.

I have no idea what Septentrio's OSNMA algorithm is like.

Best!
